from __future__ import annotations

MAX_SEARCH_RESULTS = 100
DEFAULT_DEEP_SEARCH_RESULTS = 50
MAX_SEARCH_QUERY_VARIANTS = 5
MAX_SEARCH_PAGES_PER_QUERY = 6
MAX_SEARCH_REQUESTS = MAX_SEARCH_QUERY_VARIANTS * MAX_SEARCH_PAGES_PER_QUERY
MAX_SEARCH_PAGE_ITEMS = 50
MAX_SEARCH_ENRICHED_MEDIA = 150
MAX_MEDIA_COMMENTS = 100
MAX_MEDIA_COMMENTS_PAGE_SIZE = 50
MAX_PROFILE_COLLECTION_ITEMS = 200
MAX_PROFILE_COLLECTION_PAGE_SIZE = 24
MAX_PROFILE_COLLECTION_PAGES = 20
MAX_DAYS_BACK = 30
